apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:8.9.1-community
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: sonarqube     
  type: LoadBalancer
